version: "3.9"

services:
  backend:
    build: .
    container_name: arcevents-backend
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - mongo
    restart: always

  mongo:
    image: mongo:7
    container_name: arcevents-mongo
    volumes:
      - mongo_data:/data/db
    restart: always

volumes:
  mongo_data:
